dist: trusty
sudo: required
language: node_js
node_js:
- "11"

os:
- linux

jobs:
  include:
  - stage: install
    script: npm install
    skip_cleanup: true
  - stage: test
    script: npm run test
    skip_cleanup: true
  - stage: release
    node_js: lts/*
    deploy:
      - provider: script
        script: npm run release
        skip_cleanup: true
        on:
          branch: betac
      - provider: script
        script: npm run release
        skip_cleanup: true
        on:
          branch: beta          