dist: trusty
language: node_js
node_js:
- "11"

os:
- linux

jobs:
  include:
  - stage: install
    script: npm install
  - stage: test
    script: npm run test
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      script: npm run release
      on:
        branch IN (master, alpha, beta) 